=== huangliliu0917/midai-pay/midai-pay-common/src/main/resources/midai-pay.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.midaigroup.com/namespace" xmlns:pay="http://www.midaigroup.com/namespace"
	elementFormDefault="qualified" attributeFormDefault="unqualified" >

	<xs:element name="midai">
		<xs:complexType>
			<xs:sequence >
				<xs:element name="field_type" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="field_id"  use="required">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="0" />
									<xs:maxInclusive value="128" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="etf_name" use="required"></xs:attribute>
						<xs:attribute name="length_type" >
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="CONST" />
									<xs:enumeration value="VAR2" />
									<xs:enumeration value="VAR3" />
									<xs:enumeration value="VAR4" />
								</xs:restriction>
							</xs:simpleType>

						</xs:attribute>
						<xs:attribute name="data_type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="ASCBCD" />
									<xs:enumeration value="BIT" />
									<xs:enumeration value="CharASCII" />
								</xs:restriction>
							</xs:simpleType>

						</xs:attribute>
						
							<xs:attribute name="length" type="xs:integer" use="required">
							</xs:attribute>
						
						<xs:attribute name="align_mode"  >
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="left" />
									<xs:enumeration value="right" />
								</xs:restriction>
							</xs:simpleType>

						</xs:attribute>
						
						<xs:attribute name="var_type" type="xs:string" >
						</xs:attribute>
						<xs:attribute name="convert" type="xs:string" >
						</xs:attribute>
						

					</xs:complexType>
				</xs:element>

				<xs:element name="message" maxOccurs="unbounded">
					<xs:complexType>		
						<xs:sequence>
							<xs:element name="field" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="index" type="xs:integer"  use="required"></xs:attribute>
									<xs:attribute name="value" type="xs:string"></xs:attribute>
									<xs:attribute name="required" type="xs:boolean"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
								
							<xs:attribute name="tpdu" type="xs:string" use="required">
							</xs:attribute>
							<xs:attribute name="head" type="xs:string" use="required">
							</xs:attribute>
							<xs:attribute name="type" type="xs:string" use="required" ></xs:attribute>
							<xs:attribute name="channel" type="xs:string" use="required"></xs:attribute>
							<xs:attribute name="id" type="xs:string" use="required" ></xs:attribute>
							

					</xs:complexType>

				</xs:element>

			</xs:sequence>

		</xs:complexType>
	</xs:element>



</xs:schema>

=== huangliliu0917/midai-pay/midai-pay-posp-service/src/main/resources/midai-pay.xml
<?xml version="1.0" encoding="UTF-8"?>
<midai xmlns="http://www.midaigroup.com/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.midaigroup.com/namespace midai-pay.xsd ">
      <field_type field_id='0'   etf_name='MSG_ID'          length_type='CONST'  data_type='ASCBCD'    length='4'/> <!-- 消息类型 -->
      <field_type field_id='1'   etf_name='BIT_MAP'         length_type='CONST'  data_type='BIT'       length='16'/> <!-- 位图 -->
      <field_type field_id='2'   etf_name='PAN'             length_type='VAR2'   data_type='ASCBCD'    length='19' align_mode="left" var_type="bin"/> <!-- 主帐号 -->
      <field_type field_id='3'   etf_name='PRO_COD'         length_type='CONST'  data_type='ASCBCD'    length='6'/> <!-- 交易处理码 -->
      <field_type field_id='4'   etf_name='TTXN_AMT'        length_type='CONST'  data_type='ASCBCD'    length='12' align_mode="right"/> <!-- 交易金额 -->
      <field_type field_id='5'   etf_name='SetAmt'          length_type='CONST'  data_type='ASCBCD'    length='12'/> <!-- 结算金额:暂不使用 -->
      <field_type field_id='6'   etf_name='BilAmt'          length_type='CONST'  data_type='ASCBCD'    length='12'/> <!-- 持卡人扣账金额:暂不使用 -->
      <field_type field_id='7'   etf_name='TmsTim'          length_type='CONST'  data_type='ASCBCD'    length='10'/> <!-- 交易传输时间:暂不使用 -->
      <field_type field_id='8'   etf_name='F8'              length_type='CONST'  data_type='ASCBCD'    length='10'/> <!-- 暂不使用 -->
      <field_type field_id='9'   etf_name='SetRat'          length_type='CONST'  data_type='ASCBCD'    length='8'/>  <!-- 结算汇率:暂不使用 -->
      <field_type field_id='10'  etf_name='BilRat'          length_type='CONST'  data_type='ASCBCD'    length='8'/>  <!-- 持卡人扣款汇率:暂不使用 -->
      <field_type field_id='11'  etf_name='CSEQ_NO'         length_type='CONST'  data_type='ASCBCD'    length='6'/>  <!-- 系统跟踪号 -->
      <field_type field_id='12'  etf_name='CTXN_TM'         length_type='CONST'  data_type='ASCBCD'    length='6'/>  <!-- 受卡方所在地时间 -->
      <field_type field_id='13'  etf_name='CTXN_DT'         length_type='CONST'  data_type='ASCBCD'    length='4'/>  <!-- 受卡方所在地日期 -->
      <field_type field_id='14'  etf_name='EXP_DT'          length_type='CONST'  data_type='ASCBCD'    length='4'/>  <!-- 卡有效期 -->
      <field_type field_id='15'  etf_name='STL_DAT'         length_type='CONST'  data_type='ASCBCD'    length='4'/>  <!-- 清算日期 -->
      <field_type field_id='16'  etf_name='ConDat'          length_type='CONST'  data_type='ASCBCD'    length='4'/>  <!-- 兑换日期:暂不使用 -->
      <field_type field_id='17'  etf_name='F17'             length_type='VAR2'  data_type='CharASCII'  length='99'/>  <!-- 中行交换中心的清算日期:暂不使用 -->
      <field_type field_id='18'  etf_name='MCC_CD'          length_type='CONST'  data_type='ASCBCD'    length='4'/>  <!-- 商户类型:暂不使用 -->
      <field_type field_id='19'  etf_name='CtyCod'          length_type='CONST'  data_type='ASCBCD'    length='3'/>  <!-- 暂不使用:受理国家代码 -->
      <field_type field_id='20'  etf_name='F20'             length_type='CONST'  data_type='ASCBCD'    length='3'/>  <!-- 暂不使用:暂不使用 -->
      <field_type field_id='21'  etf_name='F21'             length_type='CONST'  data_type='ASCBCD'    length='10'/> <!-- 暂不使用 -->
      <field_type field_id='22'  etf_name='IN_MOD'          length_type='CONST'  data_type='ASCBCD'    length='3' align_mode="left"/>  <!-- 服务点输入方式码 -->
      <field_type field_id='23'  etf_name='SEP_NUM'         length_type='CONST'  data_type='ASCBCD'    length='3'/>  <!-- 卡片序列号 -->
      <field_type field_id='24'  etf_name='F24'             length_type='CONST'  data_type='ASCBCD'    length='32'/>  <!-- 国际网络标识域:暂不使用 -->
      <field_type field_id='25'  etf_name='CON_MOD'         length_type='CONST'  data_type='ASCBCD'    length='2'/>  <!-- 服务点条件码 -->
      <field_type field_id='26'  etf_name='PIN_CAP_CODE'    length_type='CONST'  data_type='ASCBCD'    length='2'/>  <!-- 服务点PIN获取码 -->
      <field_type field_id='27'  etf_name='TXN_MCC_CD'      length_type='CONST'  data_type='ASCBCD'    length='3'/>  <!-- 指定费率模板 -->
      <field_type field_id='28'  etf_name='FeeAmt'          length_type='CONST'  data_type='ASCBCD'    length='1'/>  <!-- 暂不使用 手续费-->
      <field_type field_id='29'  etf_name='F29'             length_type='CONST'  data_type='CharASCII' length='10'/> <!-- 暂不使用 -->
      <field_type field_id='30'  etf_name='F30'             length_type='VAR3'   data_type='CharASCII' length='512' var_type="bin" convert="hex"/> <!-- 解磁道KEY -->
      <field_type field_id='31'  etf_name='F31'             length_type='CONST'  data_type='CharASCII' length='10'/> <!-- 暂不使用 -->
      <field_type field_id='32'  etf_name='ACQ_NO'          length_type='VAR2'   data_type='ASCBCD'    length='11' align_mode="left" var_type="bin"/> <!-- 受理方标识码 -->
      <field_type field_id='33'  etf_name='FOR_COD'         length_type='VAR2'   data_type='ASCBCD'    length='11' var_type="bin"/> <!-- 暂不使用 发送机构标识码-->
      <field_type field_id='34'  etf_name='SPE_USE'         length_type='VAR3'   data_type='CharASCII' length='28' var_type="bin"/> <!-- 银盛特色交易使用 -->
      <field_type field_id='35'  etf_name='TRACK_2'         length_type='VAR2'   data_type='ASCBCD'    length='37' align_mode="left" var_type="bin"/> <!-- 第二磁道数据 -->
      <field_type field_id='36'  etf_name='TRACK_3'         length_type='VAR3'   data_type='ASCBCD'    length='104' align_mode="left" var_type="bin"/><!-- 第三磁道数据 -->
      <field_type field_id='37'  etf_name='SREF_NO'         length_type='CONST'  data_type='CharASCII' length='12'/> <!-- 检索参考号 -->
      <field_type field_id='38'  etf_name='AUT_CD'          length_type='CONST'  data_type='CharASCII' length='6'/>  <!-- 授权标识应答码 -->
      <field_type field_id='39'  etf_name='CPSCOD'          length_type='CONST'  data_type='CharASCII' length='2'/>  <!-- 应答码 -->
      <field_type field_id='40'  etf_name='F40'             length_type='CONST'  data_type='CharASCII' length='10'/> <!-- 暂不使用 -->
      <field_type field_id='41'  etf_name='TRM_NO'          length_type='CONST'  data_type='CharASCII' length='8'/>  <!-- 受卡机终端标识码 -->
      <field_type field_id='42'  etf_name='MERC_ID'         length_type='CONST'  data_type='CharASCII' length='15'/> <!-- 受卡方标识码 -->
      <field_type field_id='43'  etf_name='MERC_NM'         length_type='CONST'  data_type='CharASCII' length='40'/> <!-- 卡接受者的名称和地址:暂不使用 -->
      <field_type field_id='44'  etf_name='ADD_DATA'        length_type='VAR2'   data_type='CharASCII' length='25' var_type="bin"/>    <!-- 附加响应数据 -->
      <field_type field_id='45'  etf_name='Track1'             length_type='VAR2'   data_type='CharASCII' length='79' var_type="bin"/> <!-- 暂不使用 第一磁道数据-->
      <!--field_type field_id='46'  etf_name='F46'             length_type='CONST'  data_type='CharASCII' length='10'/--> <!-- 暂不使用 -->
      <field_type field_id='46'  etf_name='F46'             length_type='VAR3'  data_type='CharASCII' length='10' var_type="bin" /> <!-- 暂不使用 -->
      <field_type field_id='47'  etf_name='F47'             length_type='VAR4'  data_type='CharASCII' length='9999' var_type="bin" convert="hex" /> <!-- 暂不使用 -->
      <!--field_type field_id='47'  etf_name='F47'             length_type='CONST'  data_type='CharASCII' length='10'/--> <!-- 暂不使用 -->
      <field_type field_id='48'  etf_name='PRI_USE'         length_type='VAR3'   data_type='CharASCII' length='322' var_type="bin"  align_mode="left"/>   <!-- 附加数据 -->
      <field_type field_id='49'  etf_name='CCY'             length_type='CONST'  data_type='CharASCII' length='3'/>  <!-- Field4货币代码 -->
      <field_type field_id='50'  etf_name='StlCcy'             length_type='CONST'  data_type='ASCBCD'    length='3'/>  <!-- 暂不使用 结算币种-->
      <field_type field_id='51'  etf_name='BilCcy'             length_type='CONST'  data_type='ASCBCD'    length='3'/>  <!-- 暂不使用 持卡人帐户货币币种-->
      <field_type field_id='52'  etf_name='PIN_DATA'        length_type='CONST'  data_type='BIT'       length='16'/>  <!-- 个人标识码数据 -->
      <field_type field_id='53'  etf_name='SECUR_INF'       length_type='CONST'  data_type='ASCBCD'    length='16'/> <!-- 安全控制信息 -->
      <field_type field_id='54'  etf_name='BAL_AMT'         length_type='VAR3'   data_type='CharASCII' length='20' var_type="bin"/> <!-- 余额 -->
      <field_type field_id='55'  etf_name='IC_DAT'          length_type='VAR3'   data_type='CharASCII' length='255' var_type="bin" convert='hex'/> <!-- IC卡数据域 -->
      <field_type field_id='56'  etf_name='RSP_INF'         length_type='VAR3'   data_type='CharASCII' length='999' var_type="bin"/> <!-- 应答信息 -->
      <field_type field_id='57'  etf_name='AddDat'             length_type='VAR3'   data_type='CharASCII' length='999' var_type="bin"/> <!-- 用于将来的使用 -->
      <field_type field_id='58'  etf_name='PBOC_DATA'       length_type='VAR3'   data_type='CharASCII' length='100' var_type="bin"/> <!-- PBOC电子钱包标准的交易信息 -->
      <field_type field_id='59'  etf_name='DetInq'             length_type='VAR3'   data_type='CharASCII' length='600' var_type="bin"/>   <!-- 暂不使用 明细查询数据-->
      <field_type field_id='60'  etf_name='RESE_PRI_60'     length_type='VAR3'   data_type='ASCBCD'    length='17' align_mode="left" var_type="bin"/>  <!-- 自定义域 -->
      <field_type field_id='61'  etf_name='ORI_MES'         length_type='VAR3'   data_type='ASCBCD'    length='29' align_mode="left" var_type="bin"/>  <!-- 原始信息域 -->
      <field_type field_id='62'  etf_name='RESE_PRI_62'     length_type='VAR3'   data_type='CharASCII' length='512' var_type="bin"/> <!-- 自定义域 -->
      
      <field_type field_id='63'  etf_name='RESE_PRI_63'     length_type='VAR3'   data_type='CharASCII' length='163' var_type="bin"/>  <!-- 自定义域 -->
      <field_type field_id='64'  etf_name='MAC'             length_type='CONST'  data_type='BIT'       length='16'/> <!-- MAC报文鉴别码 -->
      <field_type field_id='65'  etf_name='F65'             length_type='CONST'  data_type='CharASCII' length='10'/> <!-- 暂不使用 -->
